---
title: "My Blog"
description: |
  My first blog post / Credit: NCEAS Tidy Coral.
author:
  - name: Unknown
date: 08-16-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(janitor)
library(skimr)
library(stringr)
```



```{r}
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'

benthic_raw <- read_csv(benthic_url) 

head(benthic_raw)

benthic <- benthic_raw %>%
  janitor::clean_names()

names(benthic)

benthic <- benthic %>%
  select(id_name, point, x, y, id_date)

head(benthic)

benthic <- benthic %>%
  mutate(date = stringr::str_remove_all(id_date, "#"))

summary(benthic)

skimr::skim(benthic)

ggplot(benthic, aes(date, fill = id_name)) +
         geom_bar()


```


Distill is a publication format for scientific and technical writing, native to the web.

Learn more about using Distill at <https://rstudio.github.io/distill>.


